import CategoryRoute from "./categoryRoute.js";
import brandRoute from "./brandRoute.js";
import SubCategoryRoute from "./subCategoryRoute.js";
import productRoute from "./productRoute.js";
import authRoute from "./authRoute.js";
import userRoute from "./userRoute.js";
import reviewRoute from "./reviewRoute.js";
import wishListRoute from "./wishListRoute.js";
import addressesRoute from "./addressesRoute.js";
import coponRoute from "./coponRoute.js";
import cartRoute from "./cartRoute.js";
import orderRoute from "./orderRoute.js";
const mountRoutes = (app) => {
  app.use("/api/v1/categories", CategoryRoute);
  app.use("/api/v1/subcategories", SubCategoryRoute);
  app.use("/api/v1/brands", brandRoute);
  app.use("/api/v1/products", productRoute);
  app.use("/api/v1/auth", authRoute);
  app.use("/api/v1/users", userRoute);
  app.use("/api/v1/reviews", reviewRoute);
  app.use("/api/v1/wishlist", wishListRoute);
  app.use("/api/v1/addresses", addressesRoute);
  app.use("/api/v1/copons", coponRoute);
  app.use("/api/v1/cart", cartRoute);
  app.use("/api/v1/orders", orderRoute);
};
export default mountRoutes;
